name: Sync Backend to Hugging Face Spaces

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  sync-to-space:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Push Subfolder directly to Hugging Face
        uses: andstor/copycat-action@v3
        with:
          personal_token: ${{ secrets.HF_TOKEN }}
          src_path: 'backend/solarcrm/'
          dst_path: '/'
          dst_owner: 'archanapriya'
          dst_repo_name: 'solar-crm-backend'
          dst_repo_type: 'space'
          dst_branch: 'main'
          clean: true
          file_filter: '*'
